/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Studio = {
  _id: string
  _type: 'studio'
  _createdAt: string
  _updatedAt: string
  _rev: string
  carousel?: Array<{
    mainTitle?: string
    subtitle?: string
    duration?: string
    review?: number
    price?: number
    buttonCTA?: string
    illustrations?: Array<{
      _ref: string
      _type: 'reference'
      _weak?: boolean
      _key: string
      [internalGroqTypeReferenceTo]?: 'illustration'
    }>
    _key: string
  }>
  videoTitle?: Array<{
    keyTitle?: string
    title?: string
    _key: string
  }>
  videoCTA?: Array<{
    keyTitle?: string
    title?: string
    _key: string
  }>
  faqs?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'faqs'
  }>
  seo?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'seo'
  }
}

export type Faqs = {
  _id: string
  _type: 'faqs'
  _createdAt: string
  _updatedAt: string
  _rev: string
  question?: string
  answer?: string
}

export type Application = {
  _id: string
  _type: 'application'
  _createdAt: string
  _updatedAt: string
  _rev: string
  job?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'job'
  }
  slug?: Slug
  recruiter?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'recruiter'
  }
  candidate?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'candidate'
  }
  applicationDate?: string
  status?: 'pending' | 'underReview' | 'accepted' | 'rejected'
}

export type Recruiter = {
  _id: string
  _type: 'recruiter'
  _createdAt: string
  _updatedAt: string
  _rev: string
  firstName?: string
  lastName?: string
  sector?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'sector'
  }
  company?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'company'
  }
}

export type JobSkill = {
  _id: string
  _type: 'jobSkill'
  _createdAt: string
  _updatedAt: string
  _rev: string
  slug?: Slug
  job?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'job'
  }
  skill?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'skill'
  }
}

export type Job = {
  _id: string
  _type: 'job'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'p' | 'blockquote'
        listItem?: 'bullet' | 'numbered'
        markDefs?: Array<
          | {
              reference?: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'content'
              }
              _type: 'internalLink'
              _key: string
            }
          | {
              href?: string
              _type: 'externalLink'
              _key: string
            }
          | {
              text?: string
              url?: string
              _type: 'source'
              _key: string
            }
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        image?: {
          asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          }
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
        alt?: string
        caption?: string
        _type: 'figure'
        _key: string
      }
  >
  company?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'company'
    sector: {
      sectorName: string
    }
    name: string
    logo: object
    illustrations:any
  }
  location?: string
  publicationDate?: string
  expirationDate?: string
  experience?: 'none' | '1-3' | '3-5' | '5+'
  contract?: 'full_time' | 'part_time' | 'freelance' | 'internship'
  salary?: 'competitive' | 'specify_amount'
  salaryDetails?: {
    minSalary?: number
    maxSalary?: number
  }
  level?: 'intern' | 'junior' | 'mid' | 'senior'
  JobPost?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
    }
    _type: 'file'
  }
}

export type Company = {
  _id: string
  _type: 'company'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  email?: string
  sector?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'sector'
  }
  illustrations?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'illustration'
  }>
}

export type Sector = {
  _id: string
  _type: 'sector'
  _createdAt: string
  _updatedAt: string
  _rev: string
  sectorName?: string
}

export type CandidateSkill = {
  _id: string
  _type: 'candidateSkill'
  _createdAt: string
  _updatedAt: string
  _rev: string
  slug?: Slug
  candidate?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'candidate'
  }
  skill?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'skill'
  }
}

export type Skill = {
  _id: string
  _type: 'skill'
  _createdAt: string
  _updatedAt: string
  _rev: string
  SkillName?: string
  Subskills?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'skill'
  }>
}

export type Candidate = {
  _id: string
  _type: 'candidate'
  _createdAt: string
  _updatedAt: string
  _rev: string
  clerkId?: string
  firstName?: string
  lastName?: string
  email?: string
  phone?: string
  address?: string
  birthday?: string
  city?: string
  gender?: 'male' | 'female' | 'other'
  InterestedSector?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'sector'
  }>
  CV?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
    }
    _type: 'file'
  }
}

export type Footer = {
  _id: string
  _type: 'footer'
  _createdAt: string
  _updatedAt: string
  _rev: string
  socialLinks?: SocialMedia
  sitemapLinks?: Array<{
    label?: string
    url?: string
    priority?: number
    changefreq?: 'always' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'never'
    _key: string
  }>
  copyrightText?: string
  extraSections?: Array<{
    title?: string
    content?: Array<
      | {
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'p' | 'blockquote'
          listItem?: 'bullet' | 'numbered'
          markDefs?: Array<
            | {
                reference?: {
                  _ref: string
                  _type: 'reference'
                  _weak?: boolean
                  [internalGroqTypeReferenceTo]?: 'content'
                }
                _type: 'internalLink'
                _key: string
              }
            | {
                href?: string
                _type: 'externalLink'
                _key: string
              }
            | {
                text?: string
                url?: string
                _type: 'source'
                _key: string
              }
          >
          level?: number
          _type: 'block'
          _key: string
        }
      | {
          image?: {
            asset?: {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
            }
            hotspot?: SanityImageHotspot
            crop?: SanityImageCrop
            _type: 'image'
          }
          alt?: string
          caption?: string
          _type: 'figure'
          _key: string
        }
    >
    _key: string
  }>
}

export type Publication = {
  _id: string
  _type: 'publication'
  _createdAt: string
  _updatedAt: string
  _rev: string
  image?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'imageAsset'
  }
  title?: string
  slug?: Slug
  SubTitle?: string
  description?: string
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'p' | 'blockquote'
        listItem?: 'bullet' | 'numbered'
        markDefs?: Array<
          | {
              reference?: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'content'
              }
              _type: 'internalLink'
              _key: string
            }
          | {
              href?: string
              _type: 'externalLink'
              _key: string
            }
          | {
              text?: string
              url?: string
              _type: 'source'
              _key: string
            }
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        image?: {
          asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          }
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
        alt?: string
        caption?: string
        _type: 'figure'
        _key: string
      }
  >
  publicationDate?: string
  pdfFile?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
    }
    _type: 'file'
  }
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type Accueil = {
  _id: string
  _type: 'Accueil'
  _createdAt: string
  _updatedAt: string
  _rev: string
  image?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'imageAsset'
  }
  title?: string
  slug?: Slug
  SubTitle?: string
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'p' | 'blockquote'
        listItem?: 'bullet' | 'numbered'
        markDefs?: Array<
          | {
              reference?: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'content'
              }
              _type: 'internalLink'
              _key: string
            }
          | {
              href?: string
              _type: 'externalLink'
              _key: string
            }
          | {
              text?: string
              url?: string
              _type: 'source'
              _key: string
            }
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        image?: {
          asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          }
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
        alt?: string
        caption?: string
        _type: 'figure'
        _key: string
      }
  >
}

export type ActusEvents = {
  _id: string
  _type: 'ActusEvents'
  _createdAt: string
  _updatedAt: string
  _rev: string
  image?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'imageAsset'
  }
  title?: string
  slug?: Slug
  SubTitle?: string
  description?: string
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'p' | 'blockquote'
        listItem?: 'bullet' | 'numbered'
        markDefs?: Array<
          | {
              reference?: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'content'
              }
              _type: 'internalLink'
              _key: string
            }
          | {
              href?: string
              _type: 'externalLink'
              _key: string
            }
          | {
              text?: string
              url?: string
              _type: 'source'
              _key: string
            }
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        image?: {
          asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          }
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
        alt?: string
        caption?: string
        _type: 'figure'
        _key: string
      }
  >
  author?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'author'
  }
  tags?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'tag'
  }>
  publicationDate?: string
  timeToRead?: number
}

export type Communiques = {
  _id: string
  _type: 'communiques'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  SubTitle?: string
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'p' | 'blockquote'
        listItem?: 'bullet' | 'numbered'
        markDefs?: Array<
          | {
              reference?: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'content'
              }
              _type: 'internalLink'
              _key: string
            }
          | {
              href?: string
              _type: 'externalLink'
              _key: string
            }
          | {
              text?: string
              url?: string
              _type: 'source'
              _key: string
            }
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        image?: {
          asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          }
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
        alt?: string
        caption?: string
        _type: 'figure'
        _key: string
      }
  >
  socialMedia?: SocialMedia
  excerpt?: string
  status?: 'draft' | 'published' | 'archived'
  author?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'author'
  }
  tags?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'tag'
  }>
  publishedAt?: string
  illustrations?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'illustration'
  }>
  isDisplayedOnHome?: boolean
}

export type Tag = {
  _id: string
  _type: 'tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  description?: string
}

export type Presentation = {
  _id: string
  _type: 'presentation'
  _createdAt: string
  _updatedAt: string
  _rev: string
  slug?: Slug
  imagePresentation?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'imageAsset'
  }
  about?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'aboutUs'
  }
  faqs?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'faqs'
  }>
  seo?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'seo'
  }
}

export type Blog = {
  _id: string
  _type: 'blog'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'p' | 'blockquote'
        listItem?: 'bullet' | 'numbered'
        markDefs?: Array<
          | {
              reference?: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'content'
              }
              _type: 'internalLink'
              _key: string
            }
          | {
              href?: string
              _type: 'externalLink'
              _key: string
            }
          | {
              text?: string
              url?: string
              _type: 'source'
              _key: string
            }
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        image?: {
          asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          }
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
        alt?: string
        caption?: string
        _type: 'figure'
        _key: string
      }
  >
  description?: string
  illustrations?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'illustration'
  }>
  readingTime?: string
  publishedAt?: string
  seo?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'seo'
  }
  tags?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'tag'
  }>
  author?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'author'
  }
  category?: 'official' | 'community'
  isDisplayedOnHome?: boolean
}

export type Seo = {
  _id: string
  _type: 'seo'
  _createdAt: string
  _updatedAt: string
  _rev: string
  metaTitle?: string
  slug?: Slug
  description?: string
  keywords?: Array<string>
  openGraph?: {
    title?: string
    description?: string
    image?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'imageAsset'
    }
  }
  twitter?: {
    title?: string
    description?: string
    image?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'imageAsset'
    }
    cardType?: 'summary' | 'summary_large_image' | 'photo' | 'video' | 'gallery'
    site?: string
    creator?: string
  }
  canonicalUrl?: string
  noindex?: boolean
  nofollow?: boolean
  robots?: Array<string>
}

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'p' | 'blockquote'
      listItem?: 'bullet' | 'numbered'
      markDefs?: Array<
        | {
            reference?: {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              [internalGroqTypeReferenceTo]?: 'content'
            }
            _type: 'internalLink'
            _key: string
          }
        | {
            href?: string
            _type: 'externalLink'
            _key: string
          }
        | {
            text?: string
            url?: string
            _type: 'source'
            _key: string
          }
      >
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      image?: {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
      }
      alt?: string
      caption?: string
      _type: 'figure'
      _key: string
    }
>

export type AuthorReference = {
  _type: 'reference'
  _ref: string
  _weak?: boolean
}

export type Content = {
  _type: 'content'
  title?: string
  slug?: Slug
  SubTitle?: string
  body?: BlockContent
  socialMedia?: SocialMedia
  excerpt?: string
  status?: 'draft' | 'published' | 'archived'
  author?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'author'
  }
  tags?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'tag'
  }>
}

export type Author = {
  _id: string
  _type: 'author'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  bio?: string
  image?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'illustration'
  }
  social?: {
    twitter?: string
    instagram?: string
  }
  coAuthors?: Array<
    {
      _key: string
    } & AuthorReference
  >
}

export type Illustration = {
  _id: string
  _type: 'illustration'
  _createdAt: string
  _updatedAt: string
  _rev: string
  imageAsset?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'imageAsset'
  }
  caption?: string
  isCoverImage?: boolean
  isFeaturedImage?: boolean
}

export type ImageAsset = {
  _id: string
  _type: 'imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  alt?: string
  credit?: string
}

export type SocialMedia = {
  _type: 'socialMedia'
  facebook?: string
  twitter?: string
  linkedin?: string
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type AboutUs = {
  _id: string
  _type: 'aboutUs'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  description?: string
  mission?: string
  vision?: string
  values?: string
}

export type MediaTag = {
  _id: string
  _type: 'media.tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type AllSanitySchemaTypes =
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | Geopoint
  | Studio
  | Faqs
  | Application
  | Recruiter
  | JobSkill
  | Job
  | Company
  | Sector
  | CandidateSkill
  | Skill
  | Candidate
  | Footer
  | Publication
  | SanityFileAsset
  | Accueil
  | ActusEvents
  | Communiques
  | Tag
  | Presentation
  | Blog
  | Seo
  | BlockContent
  | AuthorReference
  | Content
  | Author
  | Illustration
  | ImageAsset
  | SocialMedia
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImageAsset
  | SanityAssetSourceData
  | SanityImageMetadata
  | AboutUs
  | MediaTag
  | Slug
export declare const internalGroqTypeReferenceTo: unique symbol
